"""init 32 tables (8 domains)

Revision ID: f98e304f3623
Revises: 
Create Date: 2026-08-19 10:49:22.170539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98e304f3623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content_html', sa.Text(), nullable=False, comment='正文'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='all/dealer'),
    sa.Column('dealer_ids', sa.JSON(), nullable=True, comment='指定经销商 JSON'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft/published'),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True, comment='发布时间'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='经销商公告'
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户（可空=游客）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='visit/designer/measure/case_design'),
    sa.Column('case_id', sa.Integer(), nullable=True, comment='关联案例'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='关联产品'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('store_id', sa.Integer(), nullable=True, comment='门店'),
    sa.Column('expect_date', sa.Date(), nullable=False, comment='期望日期'),
    sa.Column('expect_time', sa.String(length=20), nullable=True, comment='期望时段'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/confirmed/done/cancelled'),
    sa.Column('admin_note', sa.String(length=500), nullable=True, comment='后台备注'),
    sa.Column('handler_id', sa.Integer(), nullable=True, comment='处理人'),
    sa.Column('contract_id', sa.Integer(), nullable=True, comment='转签单（V1.9 闭环）'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    # PG 兼容（数据库文档 §2.4）：contract_id 循环外键改由 post_upgrade 追加（SQLite 外键不强制）
    sa.ForeignKeyConstraint(['handler_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='预约'
    )
    op.create_table('banners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False, comment='图片（1920×780）'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='标题'),
    sa.Column('subtitle', sa.String(length=200), nullable=True, comment='副标题'),
    sa.Column('button_text', sa.String(length=20), nullable=True, comment='按钮文字'),
    sa.Column('link_url', sa.String(length=255), nullable=True, comment='跳转链接'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='首页Banner'
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='案例标题'),
    sa.Column('cover', sa.String(length=255), nullable=True, comment='封面'),
    sa.Column('area', sa.String(length=50), nullable=True, comment='户型面积（如 130㎡）'),
    sa.Column('house_type', sa.String(length=50), nullable=True, comment='户型结构'),
    sa.Column('style_tags', sa.String(length=100), nullable=True, comment='风格标签'),
    sa.Column('space', sa.String(length=50), nullable=True, comment='所属空间'),
    sa.Column('location_desc', sa.String(length=100), nullable=True, comment='脱敏描述（如 广州·130㎡三居室）'),
    sa.Column('content_html', sa.Text(), nullable=False, comment='图文正文'),
    sa.Column('product_ids', sa.JSON(), nullable=True, comment='关联产品 ID 数组'),
    sa.Column('is_engineering', sa.Boolean(), nullable=False, comment='是否工程案例'),
    sa.Column('customer_review', sa.Text(), nullable=True, comment='脱敏客户评价'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='实景案例'
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_no', sa.String(length=30), nullable=False, comment='签单号（唯一，TP+日期+序号）'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户'),
    sa.Column('customer_name', sa.String(length=50), nullable=False, comment='客户名'),
    sa.Column('customer_phone', sa.String(length=20), nullable=False, comment='客户电话'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='offline/appointment/dealer_intent'),
    sa.Column('appointment_id', sa.Integer(), nullable=True, comment='来源预约'),
    sa.Column('items', sa.JSON(), nullable=False, comment='产品清单 JSON 快照（ADR-003）'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='总金额（NULL=待定）'),
    sa.Column('deposit', sa.Numeric(precision=12, scale=2), nullable=True, comment='定金'),
    sa.Column('payment_plan', sa.JSON(), nullable=True, comment='付款计划 JSON'),
    sa.Column('delivery_date', sa.Date(), nullable=True, comment='交付日期'),
    sa.Column('store_id', sa.Integer(), nullable=True, comment='门店'),
    sa.Column('admin_id', sa.Integer(), nullable=True, comment='录单人'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='signed/producing/delivered/done/cancelled'),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True, comment='取消原因'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='取消时间'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['staff_users.id'], ),
    # PG 兼容（数据库文档 §2.4）：appointment_id 循环外键改由 post_upgrade 追加（SQLite 外键不强制）
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no'),
    comment='签单'
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='上级部门（NULL=顶级）'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='部门（部门树）'
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('file_url', sa.String(length=255), nullable=False, comment='文件 URL'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='合作政策文档'
    )
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False, comment='问题'),
    sa.Column('answer', sa.Text(), nullable=False, comment='答案'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='常见问题'
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='职位'),
    sa.Column('department', sa.String(length=50), nullable=True, comment='部门'),
    sa.Column('location', sa.String(length=50), nullable=True, comment='地点'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型（社会/校园）'),
    sa.Column('duty', sa.Text(), nullable=True, comment='职责'),
    sa.Column('requirement', sa.Text(), nullable=True, comment='要求'),
    sa.Column('salary', sa.String(length=50), nullable=True, comment='薪资'),
    sa.Column('tags', sa.String(length=100), nullable=True, comment='标签'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active/closed'),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True, comment='发布时间'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='招聘岗位'
    )
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False, comment='年份'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='事件标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='事件描述'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='配图'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='发展历程'
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='company_news/industry_news'),
    sa.Column('cover', sa.String(length=255), nullable=True, comment='封面图'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='摘要'),
    sa.Column('content_html', sa.Text(), nullable=False, comment='富文本正文'),
    sa.Column('author', sa.String(length=50), nullable=True, comment='作者'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='来源（转载标注）'),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True, comment='发布时间（倒序）'),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True, comment='截止时间（NULL=长期）'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='是否发布（布尔 0/1）'),
    sa.Column('is_top', sa.Boolean(), nullable=False, comment='是否置顶/推荐'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='新闻'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=30), nullable=False, comment='RBAC 标识'),
    sa.Column('permissions', sa.JSON(), nullable=False, comment='权限码数组'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('role_name'),
    comment='角色（RBAC）'
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='系列名'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='系列图'),
    sa.Column('intro', sa.String(length=255), nullable=True, comment='简介'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序（小在前）'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='产品系列'
    )
    op.create_table('site_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False, comment='配置键（业务唯一键）'),
    sa.Column('value', sa.JSON(), nullable=False, comment='配置值 JSON'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    comment='站点配置(键值表)'
    )
    op.create_table('spaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='空间名'),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='图标'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='空间分类'
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='门店名'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='地址'),
    sa.Column('lat', sa.Numeric(precision=10, scale=6), nullable=True, comment='纬度'),
    sa.Column('lng', sa.Numeric(precision=10, scale=6), nullable=True, comment='经度'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='电话'),
    sa.Column('business_hours', sa.String(length=100), nullable=True, comment='营业时间'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='门店图'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='门店'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='登录账号（手机号）'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='bcrypt；验证码登录可为空'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像 URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user/dealer'),
    sa.Column('dealer_verified_at', sa.DateTime(timezone=True), nullable=True, comment='经销商认证通过时间'),
    sa.Column('dealer_discount', sa.Numeric(precision=5, scale=2), nullable=True, comment='默认折扣率 0.00~1.00'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    comment='前台用户（客户）'
    )
    op.create_table('visit_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('stat_type', sa.String(length=20), nullable=False, comment='类型（page/product/event）'),
    sa.Column('target', sa.String(length=255), nullable=False, comment='对象'),
    sa.Column('pv', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('uv', sa.Integer(), nullable=False, comment='访客数'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'stat_type', 'target', name='uq_visit_stats'),
    comment='访问统计(日聚合)'
    )
    op.create_table('dealer_purchase_intents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False, comment='经销商（users）'),
    sa.Column('items', sa.JSON(), nullable=False, comment='采购清单 JSON'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending_quote/quoted/confirmed/closed'),
    sa.Column('quote', sa.JSON(), nullable=True, comment='报价 JSON'),
    sa.Column('contract_id', sa.Integer(), nullable=True, comment='转正式签单'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='经销商采购意向'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='产品名'),
    sa.Column('product_no', sa.String(length=50), nullable=False, comment='产品编号（唯一）'),
    sa.Column('series_id', sa.Integer(), nullable=False, comment='所属系列'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='所属空间分类主分类'),
    sa.Column('style_tags', sa.String(length=100), nullable=True, comment='风格标签（逗号分隔）'),
    sa.Column('specs', sa.JSON(), nullable=True, comment='规格参数 JSON'),
    sa.Column('retail_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='零售参考价（NULL=按方案报价）'),
    sa.Column('dealer_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='经销商单品价；NULL 按折扣率折算'),
    sa.Column('stock', sa.Integer(), nullable=False, comment='库存'),
    sa.Column('stock_warn', sa.Integer(), nullable=False, comment='库存预警阈值'),
    sa.Column('cover_image_url', sa.String(length=255), nullable=True, comment='封面图片 URL'),
    sa.Column('images', sa.JSON(), nullable=True, comment='图集 URL 数组'),
    sa.Column('detail_html', sa.Text(), nullable=True, comment='富文本详情'),
    sa.Column('size', sa.String(length=255), nullable=True, comment='尺寸参数'),
    sa.Column('material', sa.String(length=255), nullable=True, comment='材质'),
    sa.Column('craft', sa.String(length=255), nullable=True, comment='工艺参数'),
    sa.Column('warranty', sa.String(length=255), nullable=True, comment='质保/售后说明'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='默认排序'),
    sa.Column('publish_status', sa.String(length=20), nullable=False, comment='on_shelf/off_shelf/draft'),
    sa.Column('is_top', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('is_recommend', sa.Boolean(), nullable=False, comment='首页精选'),
    sa.Column('is_new', sa.Boolean(), nullable=False, comment='新品标签'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除（PRD 7.1.2）'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_no'),
    comment='产品'
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False, comment='职位'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('education', sa.String(length=50), nullable=True, comment='学历'),
    sa.Column('school', sa.String(length=100), nullable=True, comment='学校'),
    sa.Column('work_years', sa.String(length=50), nullable=True, comment='工作年限'),
    sa.Column('attachment_url', sa.String(length=255), nullable=True, comment='附件'),
    sa.Column('intro', sa.Text(), nullable=True, comment='自我介绍'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='submitted/screened/interviewing/hired/rejected'),
    sa.Column('apply_no', sa.String(length=30), nullable=False, comment='投递查询号'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apply_no'),
    sa.UniqueConstraint('job_id', 'phone', name='uq_resumes_job_phone'),
    comment='简历投递'
    )
    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='姓名'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='邮箱'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='岗位'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='部门'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色（RBAC）'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    comment='内部员工/管理员'
    )
    op.create_table('visit_stat_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_id', sa.Integer(), nullable=False, comment='统计记录'),
    sa.Column('device_id', sa.String(length=64), nullable=False, comment='设备 UUID'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stat_id'], ['visit_stats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_id', 'device_id', name='uq_visit_stat_devices'),
    comment='UV去重明细'
    )
    op.create_table('contract_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False, comment='签单'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人'),
    sa.Column('operator', sa.String(length=20), nullable=False, comment='操作方类型'),
    sa.Column('action', sa.String(length=30), nullable=False, comment='动作'),
    sa.Column('detail', sa.JSON(), nullable=True, comment='明细 JSON'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='签单操作日志'
    )
    op.create_table('dealer_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='申请人'),
    sa.Column('company_name', sa.String(length=100), nullable=False, comment='企业名称'),
    sa.Column('credit_code', sa.String(length=50), nullable=False, comment='统一社会信用代码'),
    sa.Column('license_img', sa.String(length=255), nullable=False, comment='营业执照图片'),
    sa.Column('contact', sa.String(length=50), nullable=False, comment='联系人'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='所在地区'),
    sa.Column('reason', sa.Text(), nullable=True, comment='申请理由'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/approved/rejected'),
    sa.Column('reject_reason', sa.String(length=255), nullable=True, comment='驳回原因'),
    sa.Column('handled_by', sa.Integer(), nullable=True, comment='审核人'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True, comment='审核时间'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['handled_by'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='经销商认证申请'
    )
    op.create_table('engineering_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户'),
    sa.Column('company', sa.String(length=100), nullable=False, comment='公司'),
    sa.Column('contact', sa.String(length=50), nullable=False, comment='联系人'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='电话'),
    sa.Column('project_type', sa.String(length=20), nullable=False, comment='hotel/office/commercial/school/other'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='地点'),
    sa.Column('scale', sa.String(length=50), nullable=True, comment='规模'),
    sa.Column('deadline', sa.String(length=50), nullable=True, comment='期限'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('attachment_url', sa.String(length=255), nullable=True, comment='附件'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/designing/quoting/signed/closed'),
    sa.Column('handler_id', sa.Integer(), nullable=True, comment='处理人'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='工程定制需求'
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='收藏人'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='产品'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_favorites'),
    comment='产品收藏'
    )
    op.create_table('franchise_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='电话'),
    sa.Column('city', sa.String(length=50), nullable=False, comment='城市'),
    sa.Column('invest_amount', sa.String(length=50), nullable=True, comment='投资额度'),
    sa.Column('area', sa.String(length=50), nullable=True, comment='面积'),
    sa.Column('current_status', sa.String(length=20), nullable=True, comment='new_shop/existing_shop'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/contacted/negotiating/signed/rejected'),
    sa.Column('reject_reason', sa.String(length=255), nullable=True, comment='驳回原因'),
    sa.Column('handler_id', sa.Integer(), nullable=True, comment='处理人'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='加盟申请'
    )
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户'),
    sa.Column('company', sa.String(length=100), nullable=False, comment='公司'),
    sa.Column('contact', sa.String(length=50), nullable=False, comment='联系人'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('purpose', sa.String(length=20), nullable=False, comment='self_use/project/wholesale'),
    sa.Column('items', sa.JSON(), nullable=False, comment='询价清单 JSON 快照'),
    sa.Column('expect_time', sa.String(length=50), nullable=True, comment='期望时间'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/quoted/accepted/closed'),
    sa.Column('quote', sa.JSON(), nullable=True, comment='报价 JSON'),
    sa.Column('handler_id', sa.Integer(), nullable=True, comment='处理人'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='批量询价'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False, comment='message/consult'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='contact_page/float_window'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('category', sa.String(length=20), nullable=True, comment='分类'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/handled'),
    sa.Column('reply', sa.Text(), nullable=True, comment='回复'),
    sa.Column('handler_id', sa.Integer(), nullable=True, comment='处理人'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True, comment='处理时间'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='留言/在线咨询(双入口同表)'
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='模块'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='动作'),
    sa.Column('target', sa.String(length=100), nullable=True, comment='操作对象'),
    sa.Column('detail', sa.JSON(), nullable=True, comment='变更前后值'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='来源 IP'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='操作日志'
    )
    op.create_table('product_spaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='产品'),
    sa.Column('space_id', sa.Integer(), nullable=False, comment='空间'),
    sa.Column('is_activate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'space_id', name='uq_product_spaces'),
    comment='产品-空间关联(M:N)'
    )
    # ### end Alembic commands ###

    # ===== P6 PG 兼容补丁（数据库文档 §2.4：循环外键建表后追加；SQLite 外键不强制跳过）=====
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.create_foreign_key("fk_appointments_contracts", "appointments", "contracts", ["contract_id"], ["id"])
        op.create_foreign_key("fk_contracts_appointments", "contracts", "appointments", ["appointment_id"], ["id"])

    # ===== P6 性能索引（PRD §11.1：高频查询字段）=====
    op.create_index("ix_products_series", "products", ["series_id"])
    op.create_index("ix_products_category", "products", ["category_id"])
    op.create_index("ix_appointments_user", "appointments", ["user_id"])
    op.create_index("ix_contracts_user", "contracts", ["user_id"])
    op.create_index("ix_messages_phone", "messages", ["phone"])
    op.create_index("ix_resumes_job", "resumes", ["job_id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_spaces')
    op.drop_table('operation_logs')
    op.drop_table('messages')
    op.drop_table('inquiries')
    op.drop_table('franchise_applications')
    op.drop_table('favorites')
    op.drop_table('engineering_requests')
    op.drop_table('dealer_applications')
    op.drop_table('contract_logs')
    op.drop_table('visit_stat_devices')
    op.drop_table('staff_users')
    op.drop_table('resumes')
    op.drop_table('products')
    op.drop_table('dealer_purchase_intents')
    op.drop_table('visit_stats')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('spaces')
    op.drop_table('site_configs')
    op.drop_table('series')
    op.drop_table('roles')
    op.drop_table('news')
    op.drop_table('milestones')
    op.drop_table('jobs')
    op.drop_table('faqs')
    op.drop_table('documents')
    op.drop_table('departments')
    op.drop_table('contracts')
    op.drop_table('cases')
    op.drop_table('banners')
    op.drop_table('appointments')
    op.drop_table('announcements')
    # ### end Alembic commands ###
